### ISSUE TITLE
Node url (localhost:9944) is hardcoded. Must be taken from a web3 wallet (subwallet, polkadotjs....)

### ISSUE THREAD

**Issue by Warchant** [ggxchain/rfq-ui#33]

**Comment by AuroraLantean** [comment]
From SubWallet, PolkadotJs, and Talisman, only Talisman team has properly answered my request in their Discord channel.  Here is what they said: "this isn't something that is available in the data injected by the wallet. In substrate, it is the responsibility of the dapp to send the transaction to the rpc, so your dapp will need to have access to its own rpc url"
