### ISSUE TITLE
Create a doc with RPC calls for automated trading

### ISSUE THREAD

**Issue by uchu** [ggxchain/rfq-ui#66]
We need to create a documentation for REST calls to GGx RPCs, so users can use automatic trading scripts.

It should cover basic operations, such as deposit, withdraw, creating an order, cancelling an order, order status. And others if anything important is missed here.

DOD:

A document in a MD format showing how RPC calls can be made for trading.
It should be done in https://github.com/ggxchain/documentation , with formatting used there. When merged to main it deploys to docs.ggxchain.io

**Comment by Warchant** [comment]
Done: https://github.com/ggxchain/documentation/tree/main/src/developer-documentation/dex
