### ISSUE TITLE
Fix DEX tokenInfoes error

### ISSUE THREAD

**Issue by uchu** [ggxchain/rfq-ui#68]
When deployed on Brooklyn and Sydney DEX throws some errors. We need to get it working there.

![Image](https://github.com/ggxchain/rfq-ui/assets/5249664/b6cd7d16-6333-4c46-be36-95e873e48506)

https://dex.sydney.ggxchain.io/wallet
https://dex.brooklyn.ggxchain.io/wallet

Also "tokenInfoes" doesn't sound good.

DOD:

DEX deployed on Sydney and Brooklyn should work as expected, without throwing errors that prevent its initialisation.

**Comment by MaxVch** [comment]
I added try catch to prevent issue on console

**Comment by uchu** [comment]
@MaxVch if it doesn't influence the logics around it might work. Please create a pr. You can assign me as a reviewer
